baseURL = "/"
languageCode = "en-us"
title = "FidoCadJ"
theme = "book"
relativeURLs = true
copyright = "Everything is mine"
defaultContentLanguage = "en"

publishDir = "../docs/"

[markup.goldmark.renderer]
unsafe= true

[languages]
  [languages.en]
    title = "FidoCadJ"
    weight = 1
    languageName = "English"
    [languages.en.params]
      linkedin = "https://linkedin.com/whoever"
  [languages.it]
    title = "FidoCadJ"
    languageName = "Italiano"
    weight = 2
    [languages.it.params]
      linkedin = "https://linkedin.com/fr/whoever"
      [languages.it.params.navigation]
        help = "Aiuto"

[params]
      currentStable = "0.24.8"
      oldStable = "0.24.7"
      winStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.8/FidoCadJ-0.24.8.msi"
      macStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.8/FidoCadJ-0.24.8.dmg"
      linuxStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.8/fidocadj-0.24.8.jar"

      winOldStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.7/FidoCadJ_0.24.7_Windows.msi"
      macOldStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.7/FidoCadJ_MacOSX.dmg"
      linuxOldStableUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.7/fidocadj.jar"

      androidDevelopUrl = "http://sourceforge.net/projects/fidocadj/files/public_betas/Android/fidocadj-debug20150227.apk/download"
      userManualUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.8/manual_en.pdf"
      oldUserManualUrl = "https://github.com/DarwinNE/FidoCadJ/releases/download/v0.24.6/manual_en.pdf"


      # (Optional, default light) Sets color theme: light, dark or auto.
      # Theme 'auto' switches between dark and light modes based on browser/os preferences
      BookTheme = 'light'

      # (Optional, default true) Controls table of contents visibility on right side of pages.
      # Start and end levels can be controlled with markup.tableOfContents setting.
      # You can also specify this parameter per page in front matter.
      BookToC = true

      # (Optional, default none) Set the path to a logo for the book. If the logo is
      # /static/logo.png then the path would be 'logo.png'
      BookLogo = 'icona_fidocadj_512x512.png'

      # (Optional, default none) Set leaf bundle to render as side menu
      # When not specified file structure and weights will be used
      BookMenuBundle = '/menu'

      # (Optional, default docs) Specify section of content to render as menu
      # You can also set value to "*" to render all sections to menu
      BookSection = 'docs'

      # Set source repository location.
      # Used for 'Last Modified' and 'Edit this page' links.
      BookRepo = 'https://github.com/DarwinNE/FidoCadJ/tree/gh-pages'

      # Specifies commit portion of the link to the page's last modified commit hash for 'doc' page
      # type.
      # Required if 'BookRepo' param is set.
      # Value used to construct a URL consisting of BookRepo/BookCommitPath/<commit-hash>
      # Github uses 'commit', Bitbucket uses 'commits'
      BookCommitPath = 'commit'

      # Enable 'Edit this page' links for 'doc' page type.
      # Disabled by default. Uncomment to enable. Requires 'BookRepo' param.
      # Path must point to the site directory.
      #BookEditPath = 'edit/master/exampleSite'

      # (Optional, default January 2, 2006) Configure the date format used on the pages
      # - In git information
      # - In blog posts
      BookDateFormat = 'Jan 2, 2006'

      # (Optional, default true) Enables search function with flexsearch,
      # Index is built on fly, therefore it might slowdown your website.
      # Configuration for indexing can be adjusted in i18n folder per language.
      BookSearch = false

      # (Optional, default true) Enables comments template on pages
      # By default partials/docs/comments.html includes Disqus template
      # See https://gohugo.io/content-management/comments/#configure-disqus
      # Can be overwritten by same param in page frontmatter
      BookComments = false

      # /!\ This is an experimental feature, might be removed or changed at any time
      # (Optional, experimental, default false) Enables portable links and link checks in markdown pages.
      # Portable links meant to work with text editors and let you write markdown without {{< relref >}} shortcode
      # Theme will print warning if page referenced in markdown does not exists.
      BookPortableLinks = false

      # /!\ This is an experimental feature, might be removed or changed at any time
      # (Optional, experimental, default false) Enables service worker that caches visited pages and resources for offline use.
      BookServiceWorker = false
  [params.navigation]
    help = "Help"
