package export;

import java.awt.*;
import java.util.*;
import java.io.*;
import globals.*;
import layers.*;

/** Export in a LaTeX drawing using the pgf (Portable Graphic File) packet.
	The file should be compatible with at least the 0.65 version of the
	pgf packet.
	
	Here is an example of a file inclusion, in LaTeX:<br>
	
	-------------------------------------------------
	<pre>
	\\documentclass[10pt,a4paper]{scrreprt}
	\\usepackage[italian]{babel} 
	\\usepackage{pgf}

	\\begin{document}
	\\input{prova.pgf}
	\\end{document}
	</pre>
	-------------------------------------------------<br>

	since the prova.pgf file (generated by FidoCadJ) already contains the
	\begin{pgfpicture} and \end{pgfpicture} commands in order to work in the 
	correct environment.
	The text is not formatted, since the user should be able to use LaTeX 
	commands inside FidoCadJ to be parsed when the exported pgf file is included
	and compiled with LaTeX or pdfLaTeX.
	
	
<pre>
   Written by Davide Bucci, davbucci at tiscali dot it
   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
   </pre>

    
    @author Davide Bucci
    @version 1.0, July 2008
*/

public class ExportPGF implements ExportInterface {

	private File fileExp;
	private FileWriter fstream;
	private BufferedWriter out;
	private Vector layerV;
	private int numberPath;
	private Color actualColor;
	private double lineWidth;
	
	static final int NODE_SIZE = 1;
	static final double l_width=0.33;
	
	/** Constructor
	
		@param f the File object in which the export should be done.
		
	*/
	
	public ExportPGF (File f) throws IOException
	{
		fileExp=f;
		
		fstream = new FileWriter(fileExp);
    
		
	}
	
	/**	Called at the beginning of the export phase. Ideally, in this routine
		there should be the code to write the header of the file on which
		the drawing should be exported.
			
		@param totalSize the size of the image. Useful to calculate for example
		the	bounding box.
		@param la a LayerDesc vector describing the attributes of each 
		layer.
		@param grid the grid size
	*/
	
	public void exportStart(Dimension totalSize, Vector la, int grid)  
		throws IOException
	{ 
		
		// We need to save layers informations, since we will use them later.
		
		layerV=la;
		int i;
	    out = new BufferedWriter(fstream);
	    numberPath=0;
	    LayerDesc l;
	    Color c;
	    	    
	    int wi=totalSize.width;
	    int he=totalSize.height;
	    
	    // A basic header of the PGF file
	    
    	out.write("\\begin{pgfpicture}{0cm}{0cm}{"+wi+"pt}{"+he+"pt}\n"+
			"% Created by FidoCadJ ver. "+Globals.version+
			", export filter by Davide Bucci\n");
		out.write("\\pgfsetxvec{\\pgfpoint{1pt}{0pt}}\n");
		out.write("\\pgfsetyvec{\\pgfpoint{0pt}{1pt}}\n");
		out.write("\\pgfsetlinewidth{"+l_width+"pt}\n");
		out.write("\\pgfsetroundjoin \n");
		out.write("\\pgftranslateto{\\pgfxy(0,"+he+")}\n");
		out.write("\\begin{pgfmagnify}{1}{-1}\n");
		out.write("% Layer color definitions\n");
		for(i=0; i<layerV.size();++i) {
			l=(LayerDesc)layerV.get(i);
			c=l.getColor();
			out.write("\\definecolor{layer"+i+"}{rgb}{"+
				+Math.round(100.0*c.getRed()/255.0)/100.0+","
				+Math.round(100.0*c.getGreen()/255.0)/100.0+ ","
				+Math.round(100.0*c.getBlue()/255.0)/100.0 +"}\n");
		}
		out.write("% End of color definitions\n");
		actualColor=null;
	} 
	
	/** Called at the end of the export phase.
	*/
	public void exportEnd() 
		throws IOException
	{ 
		out.write("\\end{pgfmagnify}\n");
		out.write("\\end{pgfpicture}");
		out.close();
    
	}

	/** Called when exporting an Advanced Text primitive.
	
		@param x the x position of the beginning of the string to be written
		@param y the y position of the beginning of the string to be written
		@param sizex the x size of the font to be used
		@param sizey the y size of the font to be used
		@param fontname the font to be used
		@param isBold true if the text should be written with a boldface font
		@param isMirrored true if the text should be mirrored
		@param isItalic true if the text should be written with an italic font
		@param orientation angle of orientation (degrees)
		@param layer the layer that should be used
		@param text the text that should be written
	*/
	
	public void exportAdvText (int x, int y, int sizex, int sizey,
		String fontname, boolean isBold, boolean isMirrored, boolean isItalic,
		int orientation, int layer, String text) 
		throws IOException
	{ 
		registerColor(layer);

		
		String path;
		
		/*  THIS VERSION OF TEXT EXPORT IS NOT COMPLETE! IN PARTICULAR, 
			MIRRORING EFFECTS, ANGLES AND A PRECISE SIZE CONTROL IS NOT
			HANDLED
		*/
		
		out.write("\\begin{pgfmagnify}{1}{-1}\n");
		//out.write("\\pgftranslateto{\pgfxy(0,"+(-he)+")}\n");
		out.write("\\pgfputat{\\pgfxy("+x+","+(-y)+")}{\\pgfbox[left,top]{");	
		out.write(text);
		out.write("}}\n");

		out.write("\\end{pgfmagnify}\n");
			
		
	}
	
	/** Called when exporting a Bézier primitive.
	
		@param x1 the x position of the first point of the trace
		@param y1 the y position of the first point of the trace
		@param x2 the x position of the second point of the trace
		@param y2 the y position of the second point of the trace
		@param x3 the x position of the third point of the trace
		@param y3 the y position of the third point of the trace
		@param x4 the x position of the fourth point of the trace
		@param y4 the y position of the fourth point of the trace
		@param layer the layer that should be used
	*/
	public void exportBezier (int x1, int y1,
		int x2, int y2,
		int x3, int y3,
		int x4, int y4,
		int layer) 
		throws IOException	
	{ 		
		registerColor(layer);

		
		out.write("\\pgfmoveto{\\pgfxy("+x1+","+y1+")} \n"+
			"\\pgfcurveto{\\pgfxy("+x2+","+y2+")}{\\pgfxy("+x3+","+y3+
			")}{\\pgfxy("+x4+","+y4+")}\n"+
			"\\pgfstroke\n");
	
	}
	
	/** Called when exporting a Connection primitive.
	
		@param x the x position of the position of the connection
		@param y the y position of the position of the connection
		
		@param layer the layer that should be used
	*/
	public void exportConnection (int x, int y, int layer) 
		throws IOException
	{ 
		registerColor(layer);

		out.write("\\pgfcircle[fill]{\\pgfxy("+x+","+y+")}{"+NODE_SIZE+"pt}");
	
	}
		
	/** Called when exporting a Line primitive.
	
		@param x1 the x position of the first point of the segment
		@param y1 the y position of the first point of the segment
		@param x2 the x position of the second point of the segment
		@param y2 the y position of the second point of the segment
		
		@param layer the layer that should be used
	*/
	public void exportLine (int x1, int y1,
		int x2, int y2,
		int layer) 
		throws IOException
	{ 
		registerColor(layer);

		
		out.write("\\pgfline{\\pgfxy("+x1+","+y1+")}{\\pgfxy("+
			x2+","+y2+")}\n"); 

	}
	
	/** Called when exporting a Macro call.
		This function can just return false, to indicate that the macro should 
		be rendered by means of calling the other primitives. Please note that 
		a macro does not have a reference layer, since it is defined by its
		components.
		
		@param x the x position of the position of the macro
		@param y the y position of the position of the macro
		@param isMirrored true if the macro is mirrored
		@param orientation the macro orientation in degrees
		@param macroName the macro name
		@param macroDesc the macro description, in the FidoCad format
	*/
	public boolean exportMacro(int x, int y, boolean isMirrored, 
		int orientation, String macroName, String macroDesc,
		String name, int xn, int yn, String value, int xv, int yv)
		throws IOException
	{
		//out.write("% macro: "+macroName+"\n");
		// The macro will be expanded into primitives.
		return false; 
	}
	
	
	/** Called when exporting an Oval primitive. Specify the bounding box.
			
		@param x1 the x position of the first corner
		@param y1 the y position of the first corner
		@param x2 the x position of the second corner
		@param y2 the y position of the second corner
		@param isFilled it is true if the oval should be filled
		
		@param layer the layer that should be used
	*/	
	public void exportOval(int x1, int y1, int x2, int y2,
		boolean isFilled, int layer) 
		throws IOException
	{ 
		registerColor(layer);

		out.write("\\pgfellipse["+(isFilled?"fillstroke":"stroke")+
			"]{\\pgfxy("+(x1+x2)/2.0+","+(y1+y2)/2.0+")}{\\pgfxy("+
			Math.abs(x2-x1)/2.0+",0)}{\\pgfxy(0,"+Math.abs(y2-y1)/2.0+")}\n");
    
		
	}
		
	/** Called when exporting a PCBLine primitive.
	
		@param x1 the x position of the first point of the segment
		@param y1 the y position of the first point of the segment
		@param x2 the x position of the second point of the segment
		@param y2 the y position of the second point of the segment
		@param width the width ot the line
		@param layer the layer that should be used
	*/
	public void exportPCBLine(int x1, int y1, int x2, int y2, int width, 
		int layer) 
		throws IOException
	{ 
		registerColor(layer);

		
		out.write("\\pgfsetlinewidth{"+width+"pt}\n");
		out.write("\\pgfline{\\pgfxy("+x1+","+y1+")}{\\pgfxy("+
			x2+","+y2+")}\n");
		
		out.write("\\pgfsetlinewidth{"+l_width+"pt}\n");
	
		out.write("\\pgfellipse[fill"+
			"]{\\pgfxy("+x1+","+y1+")}{\\pgfxy("+
			width/2.0+",0)}{\\pgfxy(0,"+width/2.0+")}\n");
		out.write("\\pgfellipse[fill"+
			"]{\\pgfxy("+x2+","+y2+")}{\\pgfxy("+
			width/2.0+",0)}{\\pgfxy(0,"+width/2.0+")}\n");
	}
		
	
	/** Called when exporting a PCBPad primitive.
	
		@param x the x position of the pad 
		@param y the y position of the pad
		@param style the style of the pad (0: oval, 1: square, 2: rounded 
			square)
		@param six the x size of the pad
		@param siy the y size of the pad
		@param indiam the hole internal diameter
		@param layer the layer that should be used
	*/
	
	public void exportPCBPad(int x, int y, int style, int six, int siy, 
		int indiam, int layer, boolean onlyHole) 
		throws IOException
	{ 
		double xdd;
		double ydd;
		
		// At first, draw the pad...
		if(!onlyHole) {
			registerColor(layer);
			switch (style) {
				default:
				case 0: // Oval pad
					out.write("\\pgfellipse[fillstroke"+
						"]{\\pgfxy("+x+","+y+")}{\\pgfxy("+
						(six/2)+",0)}{\\pgfxy(0,"+
						(siy/2)+")}\n");
					 break;
				case 1:	// Square pad
					xdd=((double)x-six/2.0);
					ydd=((double)y-siy/2.0);
					out.write("\\pgfrect[fillstroke"+
						"]{\\pgfxy("+xdd+","+ydd+")}{\\pgfxy("+
						six+","+
						siy+")}\n");
					
				
					break;
				case 2:	// Rounded pad
					xdd=((double)x-six/2.0);
					ydd=((double)y-siy/2.0);
					out.write("\\pgfrect[fillstroke"+
						"]{\\pgfxy("+xdd+","+ydd+")}{\\pgfxy("+
						six+","+
						siy+")}\n");
					break;
			}
		} else {
			// ... then, drill the hole!
			if(actualColor!=Color.white) {
				actualColor=Color.white;
				out.write("\\color{white}\n");
			}
				
			out.write("\\pgfellipse[fillstroke"+
				"]{\\pgfxy("+x+","+y+")}{\\pgfxy("+
				(indiam/2)+",0)}{\\pgfxy(0,"+
				(indiam/2)+")}\n");
		}
	}
	
	/**	Called when exporting a Polygon primitive
	
		@param vertices array containing the position of each vertex
		@param nVertices number of vertices
		@param isFilled true if the polygon is filled
		@param layer the layer that should be used
	
	*/
	public void exportPolygon(Point[] vertices, int nVertices, 
		boolean isFilled, int layer) 
		throws IOException
	{ 
		registerColor(layer);

		String fill_pattern="";
		int i;
		
		
		out.write("\\pgfmoveto{\\pgfxy("+vertices[0].x+","+
			vertices[0].y+")}\n");
		for (i=1; i<nVertices; ++i) {
			out.write("\\pgflineto{\\pgfxy("+vertices[i].x+
				","+vertices[i].y+")}\n");
		
		}
		out.write("\\pgfclosepath \n");
		if(isFilled)
			out.write("\\pgffill \n");
		else
			out.write("\\pgfqstroke \n");
		
	}
		
	/** Called when exporting a Rectangle primitive.
			
		@param x1 the x position of the first corner
		@param y1 the y position of the first corner
		@param x2 the x position of the second corner
		@param y2 the y position of the second corner
		@param isFilled it is true if the rectangle should be filled
		
		@param layer the layer that should be used
	*/
	public void exportRectangle(int x1, int y1, int x2, int y2,
		boolean isFilled, int layer) 
		throws IOException
	{ 
		
		registerColor(layer);
		out.write("\\pgfmoveto{\\pgfxy("+x1+","+y1+")}\n");
		out.write("\\pgflineto{\\pgfxy("+x2+","+y1+")}\n");
		out.write("\\pgflineto{\\pgfxy("+x2+","+y2+")}\n");
		out.write("\\pgflineto{\\pgfxy("+x1+","+y2+")}\n");
		
		
		out.write("\\pgfclosepath \n");
		if(isFilled)
			out.write("\\pgffill \n");
		else
			out.write("\\pgfqstroke \n");
		
		
	}

	private void registerColor(int layer)
		throws IOException
	{
		LayerDesc l=(LayerDesc)layerV.get(layer);
		Color c=l.getColor();
		if(actualColor!=c) {
			actualColor=c;
			out.write("\\color{layer"+layer+"}\n");
		}
	}

}