#!/bin/bash
rm bin/*.class
rm bin/circuit/*.class
rm bin/clipboard/*.class
rm bin/dialogs/*.class
rm bin/export/*.class
rm bin/geom/*.class
rm bin/globals/*.class
rm bin/layers/*.class
rm bin/primitives/*.class
rm bin/timer/*.class
rm bin/toolbars/*.class
rm bin/undo/*.class