#!/bin/bash

svn delete --force bin/*.class
svn delete --force bin/net/sourceforge/fidocadj/*.class
svn delete --force doc/*.*
svn delete --force jar/fidocadj.jar
svn delete --force doc/circuit/*.* 
svn delete --force doc/circuit/controllers/*.*
svn delete --force doc/clipboard/*.* 
svn delete --force doc/dialogs/*.*
svn delete --force doc/export/*.*
svn delete --force doc/geom/*.*
svn delete --force doc/globals/*.* 
svn delete --force doc/layers/*.*
svn delete --force doc/primitives/*.* 
svn delete --force doc/timer/*.*
svn delete --force doc/toolbars/*.*
svn delete --force doc/undo/*.*
svn delete --force doc/package-list

svn delete --force bin/circuit/*.class
svn delete --force bin/circuit/controllers/*.class
svn delete --force bin/clipboard/*.class
svn delete --force bin/dialogs/*.class
svn delete --force bin/export/*.class
svn delete --force bin/geom/*.class
svn delete --force bin/globals/*.class
svn delete --force bin/layers/*.class
svn delete --force bin/primitives/*.class
svn delete --force bin/timer/*.class
svn delete --force bin/toolbars/*.class
svn delete --force bin/undo/*.class

