#!/bin/bash

# If you have a very old Java version, maybe the -Xlint:deprecation option is not recognized

# Here we check if the user has chosen a compilation which should include the Macintosh
# extensions

if [ "$1" = "mac" ]; then
  javac  -g -O -sourcepath src -classpath bin -source 1.5 -target 1.5 ./src/AppleSpecific.java -d bin
fi 


# compile FidoCadJ
javac  -g -O -sourcepath src -classpath bin -source 1.5 -target 1.5 ./src/FidoMain.java -d bin

# compile FidoReadJ applet
javac  -g -O -sourcepath src -classpath bin -source 1.5 -target 1.5 ./src/FidoReadApplet.java -d bin

# compile FidoCadJ applet
javac  -g -O -sourcepath src -classpath bin -source 1.5 -target 1.5 ./src/FidoCadApplet.java -d bin


