#!/bin/bash
cd bin
jar cvfm fidocadj.jar ../jar/Manifest.txt * **/*
	
jar i fidocadj.jar
mv fidocadj.jar ../jar

#jar cvfm fidoreadj_applet.jar ../jar/Manifest_applet.txt *.class toolbars/*.class circuit/*.class circuit/model/*.class circuit/views/*.class clipboard/*.class geom/*.class globals/*.class layers/*.class primitives/*.class timer/*.class undo/*.class graphic/*.class graphic/swing/*.class graphic/nil/*.class  net/sourceforge/fidocadj/lib/*.* net/sourceforge/fidocadj/*.class

#jar i fidoreadj_applet.jar
#mv fidoreadj_applet.jar ../jar
cd ..



