#!/bin/bash
javadoc -d doc -sourcepath src circuit clipboard dialogs export geom globals layers primitives timer toolbars undo src/FidoFrame.java src/SearchField.java src/ScrollGlassPane.java src/ScrollGestureRecognizer.java src/MacroTree.java src/AppleSpecific.java

