#!/bin/bash
javadoc -d doc -sourcepath src circuit circuit.controllers circuit.model circuit.views clipboard dialogs export geom globals graphic layers primitives timer toolbars undo src/FidoFrame.java src/*.java
