#!/bin/bash
rm bin/net/sourceforge/fidocadj/*.class
rm bin/net/sourceforge/fidocadj/layermodel/*.class
rm bin/net/sourceforge/fidocadj/librarymodel/*.class
rm bin/net/sourceforge/fidocadj/macropicker/*.class
rm bin/net/sourceforge/fidocadj/macropicker/model/*.class
rm bin/circuit/*.class
rm bin/circuit/controllers/*.class
rm bin/clipboard/*.class
rm bin/dialogs/*.class
rm bin/export/*.class
rm bin/geom/*.class
rm bin/globals/*.class
rm bin/layers/*.class
rm bin/primitives/*.class
rm bin/timer/*.class
rm bin/toolbars/*.class
rm bin/undo/*.class
rm bin/graphic/*.class
rm bin/graphic/swing/*.class
rm bin/graphic/nil/*.class

