#!/bin/bash
# javac -Xlint:deprecation -g -sourcepath src -classpath bin -source 1.4 -target 1.4 ./src/FidoFrame.java -d bin

# If you have a very old Java version, maybe the -Xlint:deprecation option is not recognized

# compile FidoCadJ
javac  -g -sourcepath src -classpath bin -source 1.4 -target 1.4 ./src/FidoMain.java -d bin

# compile FidoReadJ applet
javac  -g -sourcepath src -classpath bin -source 1.4 -target 1.4 ./src/FidoReadApplet.java -d bin

# compile FidoCadJ applet
javac  -g -sourcepath src -classpath bin -source 1.4 -target 1.4 ./src/FidoCadApplet.java -d bin


