#!/bin/bash
cd bin
jar cvfm fidocadj.jar ../Manifest.txt *.class *.properties toolbars/icons16/*.* toolbars/icons32/*.* program_icons/*.* circuit/*.class clipboard/*.class dialogs/*.class export/*.class geom/*.class globals/*.class layers/*.class primitives/*.class timer/*.class toolbars/*.class undo/*.class
mv fidocadj.jar ../jar
cd ..

#jar cvfm fidocadj_applet.jar Manifest_applet.txt bin/CircuitPanel.class bin/FCDstdlib.class bin/FidoReadApplet.class bin/MyTimer.class bin/globals.class bin/ParseSchem.class bin/mapCoordinates.class bin/sortLayer.class bin/layerDesc.class

