#!/bin/bash
# This file is only related to my installation (Davide Bucci)
 
publish_directory=/Library/WebServer/Documents/Varie/mysite/elettronica/fidocadj/
./preparemac
cp jar/fidocadj.jar $publish_directory
open $publish_directory/FidoCadJ.dmg
cp -R mac/FidoCadJ.app /Volumes/FidoCadJ/
./cleanall
cp -R . ../fidocadj_publish
rm ../fidocadj_sources.zip
zip -r ../fidocadj_sources ../fidocadj_publish
cp ../fidocadj_sources.zip $publish_directory
echo Program published on $publish_directory

