#!/bin/sh
###########################################
##                                       ##
## FidoCadj 0.24.1 gamma                 ##
##                                       ##
## 2012-June-28 by Chokewood             ##
## revision juli 1 17:39:48 UTC 2012     ##
##                                       ##
###########################################

## file to open
file_open=$1
ext_in=`echo $file_open |awk -F . '{print $2}'`

if [ "$ext_in" == "fcd" ]
  then
    echo "Opening: $file_open"
  else
    file_open=" "
fi


run_app() {

  
  if [ ! -f $HOME/.fidocadj.cfg ]
  then
    cp /usr/share/doc/fidocadj/default.cfg $HOME/.fidocadj.cfg
    echo "user .fidocadj.cfg created"
  fi
  
  setlocale="-l`cat $HOME/.fidocadj.cfg |grep -w "use_locale" |awk '{print $3}'`"

  if [ `env |grep JAVA |grep -c openjdk` -eq 1 ]
  then
      sunopts=`cat $HOME/.fidocadj.cfg |grep -w sun_oracle |awk -F = '{print $2}'`
      export _JAVA_OPTIONS=$sunopts
  else
      jdkopts=`cat $HOME/.fidocadj.cfg |grep -w openjdk |awk -F = '{print $2}'`
      export _JAVA_OPTIONS=$jdkopts
  fi
 $JAVA_HOME/bin/java -jar /usr/share/java/fidocadj/fidocadj.jar $setlocale $file_open
} # 

give_help() {
$JAVA_HOME/bin/java -jar /usr/share/java/fidocadj/fidocadj.jar -h
}



# HELP, --help, or -h
case "$1" in
        --help )
		give_help
    exit 0
  ;;

	-h )
	      give_help
    exit 0
  ;;

*) 
  run_app
  exit 0
   ;;
esac  

