#!/bin/bash

rm  doc/*.*
rm  jar/fidocadj.jar
rm  doc/circuit/*.* 
rm  doc/circuit/controllers/*.*
rm  doc/clipboard/*.* 
rm  doc/dialogs/*.*
rm  doc/export/*.*
rm  doc/geom/*.*
rm  doc/globals/*.* 
rm  doc/layers/*.*
rm  doc/primitives/*.* 
rm  doc/timer/*.*
rm  doc/toolbars/*.*
rm  doc/undo/*.*
rm  doc/package-list

rm  doc/net/sourceforge/fidocadj/*.*
rm  doc/net/sourceforge/fidocadj/layermodel/*.*
rm  doc/net/sourceforge/fidocadj/librarymodel/*.*
rm  doc/net/sourceforge/fidocadj/macropicker/*.*


rm  bin/*.class
rm  bin/net/sourceforge/fidocadj/*.class
rm  bin/net/sourceforge/fidocadj/layermodel/*.class
rm  bin/net/sourceforge/fidocadj/librarymodel/*.class
rm  bin/net/sourceforge/fidocadj/macropicker/*.class
rm  bin/net/sourceforge/fidocadj/circuit/*.class
rm  bin/net/sourceforge/fidocadj/circuit/controllers/*.class
rm  bin/net/sourceforge/fidocadj/clipboard/*.class
rm  bin/net/sourceforge/fidocadj/dialogs/*.class
rm  bin/net/sourceforge/fidocadj/export/*.class
rm  bin/net/sourceforge/fidocadj/geom/*.class
rm  bin/net/sourceforge/fidocadj/globals/*.class
rm  bin/net/sourceforge/fidocadj/layers/*.class
rm  bin/net/sourceforge/fidocadj/primitives/*.class
rm  bin/net/sourceforge/fidocadj/timer/*.class
rm  bin/net/sourceforge/fidocadj/toolbars/*.class
rm  bin/net/sourceforge/fidocadj/undo/*.class

